name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ ninja-build

    - name: Configure
      run: |
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
